### ISSUE TITLE
Edits to mozsprint post

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/old_team_site_nikola#45]
@annakrystalli: post looks good.  A few comments: 

* the links to several key images are broken
* "MozFest 2106" - 2016?
* "I got a lot out mentoring myself" - missing 'of'
* 'vidyo' - 'video'
* 'aletheia.png' - better as quoted text than image (to ensure is indexed and searchable)?
* Funny escaping of hashes in embedded tweets

**Comment by annakrystalli** [comment]
Corrected the typos and a few more I found 😬

vidyo is correct (it's the software used). I didn't like the aletheia quotation cause it made the text too big so I've left it as .png . Finally no image links are missing for me and all tweets appearing correct for me on chrome so not sure what exactly the issue is?

**Comment by willfurnass** [comment]
Merged PR #46
